import java.awt.SystemColor.text
import java.util.regex.Pattern

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/8.7/userguide/building_cpp_projects.html in the Gradle documentation.
 */

plugins {
    id("com.github.jakemarsden.git-hooks") version "0.0.2"
    id("com.diffplug.spotless") version "6.25.0"

    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}

// Configurazione base del progetto
repositories {
    mavenCentral()
}

dependencies {
    // Aggiungi qui le tue dipendenze
    implementation("com.diffplug.spotless:spotless-plugin-gradle:6.25.0")
}

// Set the target operating system and architecture for this application
application {
    targetMachines.add(machines.linux.x86_64)
}

// Configurazione Spotless per C++
spotless {
    cpp {
        target("app/src/main/cpp/*.cpp", "app/src/main/headers/*.h")
        clangFormat()
    }
}

// Configurazione Git Hooks
gitHooks {
    setHooks(mapOf("pre-commit" to "check"))
    setHooks(mapOf("commit-msg" to "conventionalCommits"))
}

fun conventionalCommits() {
    val pattern = Pattern.compile("^(feat|fix|docs|style|refactor|test|chore)(\\(.*\\))?: .{1,50}")
    val message = File(".git/COMMIT_EDITMSG").readText().trim()
    if (!pattern.matcher(message).find()) {
        throw GradleException("Commit message does not follow Conventional Commits format.")
    }
}

tasks.register("buildCMake") {
    doLast {
        exec {
            commandLine("sh", "-c", """
                mkdir -p build &&
                cd build &&
                cmake .. &&
                cmake --build .
            """)
        }
    }
}

// Assicurati che i git hooks vengano installati durante il build
tasks.getByPath(":prepareKotlinBuildScriptModel").dependsOn.add(tasks.getByName("check"))