import java.util.regex.Pattern
import groovy.json.JsonSlurper
import okio.ByteString.Companion.encode
import java.io.ByteArrayOutputStream
import java.nio.charset.Charset
import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/8.7/userguide/building_cpp_projects.html in the Gradle documentation.
 */

plugins {
    id("com.github.jakemarsden.git-hooks") version "0.0.2"
    id("com.diffplug.spotless") version "7.0.0.BETA1"

    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}

// Configurazione base del progetto
repositories {
    mavenCentral()
}

// Set the target operating system and architecture for this application
application {
    targetMachines.add(machines.linux.x86_64)
}

val chocolateyPath = "C:\\ProgramData\\chocolatey\\bin\\choco.exe"
val llvmPath = "C:\\ProgramData\\chocolatey\\lib\\llvm"

/* Install choco package manager for windows */
tasks.register("installChocolatey") {
    group = "setup"
    description = "Chocolatey Install"

    if (!File(chocolateyPath).exists()) {
        val scriptPath = file("..\\install-chocolatey.ps1").absolutePath

        println("Installing Chocolatey...")
        val returnValue = exec {
            commandLine("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", scriptPath)
            standardOutput = System.out
            errorOutput = System.err
        }.exitValue

        if (returnValue == 0)
            println("Chocolatey installed. Please, restart the prompt before using it.")
        else
            println("Problem occurs when trying to install Chocolatey.")
    } else {
        println("Chocolatey is already installed.")
    }


}

/* Install clang format via choco */
tasks.register("installDependencies") {
    dependsOn("installChocolatey")
    doFirst {
        println("Installing clang-format using Chocolatey...")
    }

    doLast {
        if (!File(llvmPath).exists()) {
            val installScriptFile = file("..\\install-llvm.ps1")
            installScriptFile.writeText("Start-Process powershell -Verb runAs -ArgumentList \"choco install llvm\"")

            val returnValue = exec {
                commandLine("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", installScriptFile)
                standardOutput = System.out
                errorOutput = System.err
            }.exitValue

            if (returnValue == 0)
                println("LLVM installed.")
            else
                println("Problem occurs when trying to install LLVM.")
        } else {
            println("LLVM is already installed.")
        }
    }
}

// Configurazione Spotless per C++
spotless {
    cpp {
        target("src/main/cpp/*.cpp", "src/main/headers/*.h")
        clangFormat("18.1.8").pathToExe("C:\\Program Files\\LLVM\\bin\\clang-format.exe")
        // Altre regole personalizzate
        trimTrailingWhitespace()
        endWithNewline()
    }
    isEnforceCheck = false // Permette al build di proseguire anche se ci sono errori di formattazione
}

// Configurazione Git Hooks
gitHooks {
    setHooks(mapOf("commit-msg" to "checkAndApplySpotlessForCpp"))
    setHooks(mapOf("commit-msg" to "conventionalCommits"))
    setHooksDirectory(layout.projectDirectory.dir("../.git/hooks"))
}


tasks.register("checkAndApplySpotlessForCpp") {
    doLast {
        // Cattura l'output del comando git diff
        val outputStream = ByteArrayOutputStream()
        exec {
            commandLine("git", "diff", "--cached", "--name-only", "--diff-filter=ACM")
            standardOutput = outputStream // Direziona l'output nel ByteArrayOutputStream
        }

        // Ottieni l'elenco dei file .cpp modificati
        val cppFiles = outputStream.toString().trim().lines().filter { it.endsWith(".cpp") }

        if (cppFiles.isNotEmpty()) {
            // Esegui spotlessCheck
            val checkResult = exec {
                commandLine("gradlew", "spotlessCheck")
                isIgnoreExitValue = true // Non fallire il build se spotlessCheck fallisce
            }

            // Se spotlessCheck fallisce, esegui spotlessApply
            if (checkResult.exitValue != 0) {
                exec {
                    commandLine("gradlew", "spotlessApply")
                }

                // Aggiungi nuovamente i file formattati al commit
                exec {
                    commandLine("git", "add", *cppFiles.toTypedArray())
                }
            }
        }
    }
}


tasks.register("conventionalCommits") {
    val pattern = Pattern.compile("^(feat|fix|docs|style|refactor|test|chore|build|ci)(\\(.*\\))?: .{1,50}")
    val message = File(".git/COMMIT_EDITMSG").readText().trim()
    if (!pattern.matcher(message).find()) {
        throw GradleException("Commit message does not follow Conventional Commits format.")
    }
}

/*tasks.register("checkBranchFiles") {
    doLast {
        val currentBranch = exec {
            commandLine("git rev-parse --abbrev-ref HEAD")
            standardOutput = ByteArrayOutputStream()
        }.toString()

        val stagedFiles = exec {
            commandLine("git diff --cached --name-only")
            standardOutput = ByteArrayOutputStream()
        }.toString().trim().split("\n")

        val nonBranchFiles = stagedFiles.stream().filter { s -> !s.startsWith("src/main/${currentBranch}/") }

        if (nonBranchFiles.toList().size > 0) {
            println("ATTENZIONE: I seguenti file non appartengono al branch corrente (${currentBranch}):")
            nonBranchFiles.forEach { el -> println(el) }

            val userInput: String = System.console().readLine("Vuoi creare una issue per questi file? (y/n): ")
            if (userInput.lowercase() == "y") {
                createIssue(currentBranch, nonBranchFiles.toList())
            } else {
                val proceed = System.console().readLine("Vuoi procedere comunque con il commit? (y/n): ")
                if (proceed.lowercase() != "y") {
                    throw GradleException("Commit abortito dall'utente.")
                }
            }
        }
    }
}

fun createIssue(branch: String, files: List<String>) {
    // Nota: Questo è un esempio semplificato. Dovresti usare una libreria HTTP appropriata
    val title = "File non appartenenti al branch ${branch}"
    val body = "I seguenti file non appartengono al branch ${branch}:\n\n" + files.forEach { s -> println(s + "\n") }

    val authToken = System.getenv("GITHUB_TOKEN") // Assicurati di avere questo token impostato
    val repoOwner = "BrunoEsposito2"
    val repoName = "DCCV"

    val url = URI("https://api.github.com/repos/${repoOwner}/${repoName}/issues").toURL()
    val connection = url.openConnection()

    connection.setRequestProperty("Authorization", "token ${authToken}")
    connection.setRequestProperty("Content-Type", "application/json")
    connection.doOutput = true // Triggers POST request

    val jsonPayload = """
    {
        "title": "${title}",
        "body": "${body}"
    }
    """

    connection.outputStream.write(jsonPayload.encode(Charset.forName("UTF-8")).toByteArray())

    val response = JsonSlurper().parse(connection.inputStream)
    println("Issue creata: ${response}")
}*/

tasks.register("buildCMake") {
    doLast {
        exec {
            commandLine("sh", "-c", """
                mkdir -p build &&
                cd build &&
                cmake .. &&
                cmake --build . &&
                cmake --install .
            """)
        }
    }
}

unitTest {
    targetMachines.add(machines.linux.x86_64)
}

// Configura cpp-application per usare l'output di CMake
tasks.withType<LinkExecutable>().configureEach {
    dependsOn("buildCMake")
    linkerArgs.addAll(listOf(
        "-L/usr/local/lib",
        "-lopencv_core",
        "-lopencv_imgproc",
        "-lopencv_objdetect",
        "-lopencv_highgui",
        "-lopencv_imgcodecs",
        "-lopencv_videoio"
    ))
    linkerArgs.add("-Wl,-rpath,/usr/local/lib")
}

tasks.withType<CppCompile>().configureEach {
    dependsOn("buildCMake")
    includes.from("/usr/local/include/opencv4")
}

// Assicurati che i git hooks vengano installati durante il build
tasks.getByPath(":prepareKotlinBuildScriptModel").dependsOn.addAll(listOf(tasks.getByName("check")))