import java.util.regex.Pattern
import groovy.json.JsonSlurper
import okio.ByteString.Companion.encode
import org.gradle.internal.impldep.org.apache.commons.io.output.ByteArrayOutputStream
import java.nio.charset.Charset
import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/8.7/userguide/building_cpp_projects.html in the Gradle documentation.
 */

plugins {
    id("com.github.jakemarsden.git-hooks") version "0.0.2"
    id("com.diffplug.spotless") version "6.25.0"

    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}

// Configurazione base del progetto
repositories {
    mavenCentral()
}

// Set the target operating system and architecture for this application
application {
    targetMachines.add(machines.linux.x86_64)
}

// Configurazione Spotless per C++
spotless {
    cpp {
        target("app/src/main/cpp/*.cpp", "app/src/main/headers/*.h")
        clangFormat()
    }
    isEnforceCheck = false // Permette al build di proseguire anche se ci sono errori di formattazione
}

// Configurazione Git Hooks
gitHooks {
    setHooks(mapOf("pre-commit" to "spotlessApply check"))
    setHooks(mapOf("commit-msg" to "conventionalCommits"))
    setHooksDirectory(layout.projectDirectory.dir("../.git/hooks"))
}

tasks.register("conventionalCommits") {
    val pattern = Pattern.compile("^(feat|fix|docs|style|refactor|test|chore)(\\(.*\\))?: .{1,50}")
    val message = File(".git/COMMIT_EDITMSG").readText().trim()
    if (!pattern.matcher(message).find()) {
        throw GradleException("Commit message does not follow Conventional Commits format.")
    }
}

tasks.register("checkBranchFiles") {
    doLast {
        val currentBranch = exec {
            commandLine("git rev-parse --abbrev-ref HEAD")
            standardOutput = ByteArrayOutputStream()
        }.toString()

        val stagedFiles = exec {
            commandLine("git diff --cached --name-only")
            standardOutput = ByteArrayOutputStream()
        }.toString().trim().split("\n")

        val nonBranchFiles = stagedFiles.stream().filter { s -> !s.startsWith("src/main/${currentBranch}/") }

        if (nonBranchFiles.toList().size > 0) {
            println("ATTENZIONE: I seguenti file non appartengono al branch corrente (${currentBranch}):")
            nonBranchFiles.forEach { el -> println(el) }

            val userInput: String = System.console().readLine("Vuoi creare una issue per questi file? (y/n): ")
            if (userInput.lowercase() == "y") {
                createIssue(currentBranch, nonBranchFiles.toList())
            } else {
                val proceed = System.console().readLine("Vuoi procedere comunque con il commit? (y/n): ")
                if (proceed.lowercase() != "y") {
                    throw GradleException("Commit abortito dall'utente.")
                }
            }
        }
    }
}

fun createIssue(branch: String, files: List<String>) {
    // Nota: Questo è un esempio semplificato. Dovresti usare una libreria HTTP appropriata
    val title = "File non appartenenti al branch ${branch}"
    val body = "I seguenti file non appartengono al branch ${branch}:\n\n" + files.forEach { s -> println(s + "\n") }

    val authToken = System.getenv("GITHUB_TOKEN") // Assicurati di avere questo token impostato
    val repoOwner = "BrunoEsposito2"
    val repoName = "DCCV"

    val url = URI("https://api.github.com/repos/${repoOwner}/${repoName}/issues").toURL()
    val connection = url.openConnection()

    connection.setRequestProperty("Authorization", "token ${authToken}")
    connection.setRequestProperty("Content-Type", "application/json")
    connection.doOutput = true // Triggers POST request

    val jsonPayload = """
    {
        "title": "${title}",
        "body": "${body}"
    }
    """

    connection.outputStream.write(jsonPayload.encode(Charset.forName("UTF-8")).toByteArray())

    val response = JsonSlurper().parse(connection.inputStream)
    println("Issue creata: ${response}")
}

tasks.register("buildCMake") {
    doLast {
        exec {
            commandLine("sh", "-c", """
                mkdir -p build &&
                cd build &&
                cmake .. &&
                cmake --build .
            """)
        }
    }
}

unitTest {
    targetMachines.add(machines.linux.x86_64)
}

// Configura cpp-application per usare l'output di CMake
tasks.withType<LinkExecutable>().configureEach {
    dependsOn("buildCMake")
    linkerArgs.addAll(listOf(
        "-L/usr/local/lib",
        "-lopencv_core",
        "-lopencv_imgproc",
        "-lopencv_objdetect",
        "-lopencv_highgui",
        "-lopencv_imgcodecs",
        "-lopencv_videoio"
    ))
    linkerArgs.add("-Wl,-rpath,/usr/local/lib")
}

tasks.withType<CppCompile>().configureEach {
    dependsOn("buildCMake")
    includes.from("/usr/local/include/opencv4")
}

// Assicurati che i git hooks vengano installati durante il build
tasks.getByPath(":prepareKotlinBuildScriptModel").dependsOn.addAll(listOf(tasks.getByName("check")))