# This is a basic workflow to help you get started with Actions
name: Example workflow
# Controls when the workflow will run
on:
  push:
    tags: '*'
    branches-ignore: # Pushes on these branches won't start a build
    - 'main'
    paths-ignore: # Pushes that change only these file won't start the workflow
    - 'README.md'
    - 'CHANGELOG.md'
    - 'LICENSE'

jobs:
  # This workflow contains a single job called "build"
  Default-Example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print Hello World
        run: echo `ls`
