# This is a basic workflow to help you get started with Actions
name: Example workflow
# Controls when the workflow will run
on:
  push:
    tags: '*'
    branches-ignore: # Pushes on these branches won't start a build
    - 'main'
    paths-ignore: # Pushes that change only these file won't start the workflow
    - 'README.md'
    - 'CHANGELOG.md'
    - 'LICENSE'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
      
    - name: Run build
      run: sudo ./gradlew build
